version: "3.9"

services:
  backend:
    build:
      context: ./backend        # Dockerfile is located
    container_name: trackvault-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://keebs:keebs@db:5432/trackvault
    volumes:
      - ./backend:/app          
    restart: always

  db:
    image: postgres:15
    container_name: trackvault-db
    restart: always
    environment:
      POSTGRES_USER: keebs
      POSTGRES_PASSWORD: keebs
      POSTGRES_DB: trackvault
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./trackvault_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    ports:
      - "5433:5432"

volumes:
  db-data:
