name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r backend/requirements.txt
      - name: Lint & type-check
        run: |
          pip install black flake8 mypy
          black --check backend/app
          flake8 backend/app
          mypy backend/app
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q backend/tests

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build
        run: |
          cd frontend
          npm ci
          npm run lint     # if you have an ESLint script
          npm run build    # or your test script
